Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04763b3055de4860b
      Tags:
        - Key: "Name"
          Value: "Simple sample"
         